/**
 * Copyright © 2016-2026 The Inferrix Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.server.dao.license;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Decodes and verifies an Inferrix licence key: {@code base64url(payloadJson).base64url(ed25519Signature)}.
 * <p>
 * The signature is verified over the ASCII bytes of the first segment exactly as received, so no JSON is
 * ever re-serialized during verification and canonicalization cannot drift from the generator.
 * <p>
 * Pure: no Spring wiring beyond {@code @Component}, no I/O, no clock.
 */
@Component
public class LicenseCodec {

    /**
     * X.509 SPKI Ed25519 public key, base64. 44 bytes of DER, so 60 base64 characters.
     * <p>
     * <b>DEVELOPMENT KEY.</b> Generated by {@code inferrix-keygen genkeypair} for this branch only; the
     * private half lives at {@code ~/inferrix-license-DEVELOPMENT-private.pem} on the generating machine,
     * outside both repositories. This is NOT the production signing key and MUST be replaced with the real
     * production public key before the first customer build. Replacing this constant invalidates every
     * licence key issued against it.
     */
    public static final String PUBLIC_KEY_BASE64 = "MCowBQYDK2VwAyEAAFwGG5aa21CbXnoG0lTFRQidH5WWl/geM9U7s/k3cW0=";

    static final int SUPPORTED_VERSION = 1;
    static final String ALGORITHM = "Ed25519";
    static final String HASH_ALGORITHM = "SHA3-256";

    /** Plan keys the platform reads. Present-but-malformed values on these keys fail closed. */
    static final List<String> KNOWN_CAPS = List.of("maxDevices", "maxAssets");

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final char[] HEX = "0123456789abcdef".toCharArray();

    private final PublicKey publicKey;

    public LicenseCodec() {
        this(PUBLIC_KEY_BASE64);
    }

    LicenseCodec(String publicKeyBase64) {
        try {
            byte[] der = Base64.getDecoder().decode(publicKeyBase64.trim());
            this.publicKey = KeyFactory.getInstance(ALGORITHM).generatePublic(new X509EncodedKeySpec(der));
        } catch (Exception e) {
            throw new IllegalStateException("Licence public key constant is not a valid " + ALGORITHM + " key", e);
        }
    }

    public LicensePayload decodeAndVerify(String key) {
        String trimmed = key == null ? "" : key.trim();
        int dot = trimmed.indexOf('.');
        if (dot < 1 || dot != trimmed.lastIndexOf('.') || dot == trimmed.length() - 1) {
            throw new LicenseException(LicenseViolation.MALFORMED, "expected two dot-separated segments");
        }
        String segment = trimmed.substring(0, dot);
        byte[] json;
        byte[] sig;
        try {
            json = Base64.getUrlDecoder().decode(segment);
            sig = Base64.getUrlDecoder().decode(trimmed.substring(dot + 1));
        } catch (IllegalArgumentException e) {
            throw new LicenseException(LicenseViolation.MALFORMED, "segments are not valid base64url");
        }
        verifySignature(segment, sig);
        return parsePayload(json);
    }

    private void verifySignature(String segment, byte[] sig) {
        try {
            Signature signature = Signature.getInstance(ALGORITHM);
            signature.initVerify(publicKey);
            signature.update(segment.getBytes(StandardCharsets.US_ASCII));
            if (!signature.verify(sig)) {
                throw new LicenseException(LicenseViolation.BAD_SIGNATURE);
            }
        } catch (LicenseException e) {
            throw e;
        } catch (Exception e) {
            throw new LicenseException(LicenseViolation.BAD_SIGNATURE, e);
        }
    }

    /** Package-private so tests can exercise payload rules without constructing a signature. */
    static LicensePayload parsePayload(byte[] json) {
        JsonNode root;
        try {
            root = MAPPER.readTree(json);
        } catch (Exception e) {
            throw new LicenseException(LicenseViolation.MALFORMED, "payload is not valid JSON");
        }
        if (root == null || !root.isObject()) {
            throw new LicenseException(LicenseViolation.MALFORMED, "payload is not a JSON object");
        }
        int version = root.path("v").asInt(-1);
        if (version != SUPPORTED_VERSION) {
            throw new LicenseException(LicenseViolation.MALFORMED, "unsupported payload version " + version);
        }
        String iid = root.path("iid").asText(null);
        if (iid == null || iid.isBlank()) {
            throw new LicenseException(LicenseViolation.MALFORMED, "iid is missing");
        }
        if (!root.path("exp").isIntegralNumber()) {
            throw new LicenseException(LicenseViolation.MALFORMED, "exp is missing or not an integer");
        }
        return new LicensePayload(
                version,
                iid,
                root.path("cust").asText(""),
                root.path("iat").isIntegralNumber() ? root.get("iat").asLong() : 0L,
                root.get("exp").asLong(),
                readPlan(root.path("plan")));
    }

    private static Map<String, Long> readPlan(JsonNode plan) {
        Map<String, Long> caps = new HashMap<>();
        if (plan.isMissingNode() || plan.isNull()) {
            return caps;
        }
        if (!plan.isObject()) {
            throw new LicenseException(LicenseViolation.MALFORMED, "plan is not a JSON object");
        }
        for (String cap : KNOWN_CAPS) {
            JsonNode value = plan.get(cap);
            if (value == null || value.isNull()) {
                continue; // absent means unlimited
            }
            if (!value.isIntegralNumber() || !value.canConvertToLong() || value.asLong() < 0) {
                throw new LicenseException(LicenseViolation.MALFORMED,
                        cap + " must be a non-negative integer");
            }
            caps.put(cap, value.asLong());
        }
        // Only KNOWN_CAPS are read. Any other plan key is ignored by construction, which is what lets a key
        // issued for a newer build still validate on an older one.
        return caps;
    }

    /** Lowercase hex SHA3-256. Must stay byte-identical to {@code Keygen.sha3Hex} in the generator. */
    public static String sha3Hex(String input) {
        try {
            byte[] digest = MessageDigest.getInstance(HASH_ALGORITHM)
                    .digest(input.getBytes(StandardCharsets.UTF_8));
            char[] out = new char[digest.length * 2];
            for (int i = 0; i < digest.length; i++) {
                out[i * 2] = HEX[(digest[i] >> 4) & 0xF];
                out[i * 2 + 1] = HEX[digest[i] & 0xF];
            }
            return new String(out);
        } catch (Exception e) {
            throw new IllegalStateException(HASH_ALGORITHM + " is unavailable", e);
        }
    }
}
