///
/// Copyright © 2016-2026 The Inferrix Authors
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

import { Injectable } from '@angular/core';
import { ActivatedRouteSnapshot } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import {
  CellActionDescriptor,
  DateEntityTableColumn,
  EntityTableColumn,
  EntityTableConfig
} from '@home/models/entity/entities-table-config.models';
import { EntityType, entityTypeResources, entityTypeTranslations } from '@shared/models/entity-type.models';
import { ReportInfo } from '@shared/models/report.models';
import { ReportService } from '@core/http/report.service';

// Table-config resolver for the report history list (/api/v2/reportInfos). Mirrors
// SchedulerEventsTableConfigResolver's structure (list-mode half of it); reports have no
// calendar view and are not created/edited here (they're generated by the scheduler /
// on-demand report actions), so addEnabled stays false.
@Injectable()
export class ReportHistoryTableConfigResolver {

  private readonly config: EntityTableConfig<ReportInfo> = new EntityTableConfig<ReportInfo>();

  constructor(private reportService: ReportService,
              private translate: TranslateService,
              private datePipe: DatePipe) {

    this.config.entityType = EntityType.REPORT;
    this.config.entityTranslations = entityTypeTranslations.get(EntityType.REPORT);
    this.config.entityResources = entityTypeResources.get(EntityType.REPORT);
    this.config.tableTitle = this.translate.instant('report.reports');
    this.config.detailsPanelEnabled = false;
    this.config.selectionEnabled = true;
    this.config.addEnabled = false;
    this.config.entitiesDeleteEnabled = true;
    this.config.entityTitle = (report) => report ? report.name : '';

    this.config.columns.push(
      new DateEntityTableColumn<ReportInfo>('createdTime', 'common.created-time', this.datePipe, '150px'),
      new EntityTableColumn<ReportInfo>('name', 'report.name', '25%'),
      new EntityTableColumn<ReportInfo>('format', 'report.format', '10%'),
      // ReportInfo/Report (common/data report/Report.java) has no template-name field, only the
      // raw templateId UUID (see report.models.ts:42 note) - bind to what actually exists.
      new EntityTableColumn<ReportInfo>('templateId', 'report.template', '25%',
        entity => entity.templateId ? String(entity.templateId) : ''),
      new EntityTableColumn<ReportInfo>('customerTitle', 'customer.customer', '25%')
    );

    this.config.deleteEntityTitle = report => this.translate.instant('report.delete-report-title', {reportName: report.name});
    this.config.deleteEntityContent = () => this.translate.instant('report.delete-report-text');
    this.config.deleteEntitiesTitle = count => this.translate.instant('report.delete-reports-title', {count});
    this.config.deleteEntitiesContent = () => this.translate.instant('report.delete-reports-text');

    this.config.entitiesFetchFunction = pageLink => this.reportService.getReportInfos(pageLink, {});
    this.config.deleteEntity = id => this.reportService.deleteReport(id.id);

    this.config.cellActionDescriptors = this.configureCellActions();
  }

  resolve(route: ActivatedRouteSnapshot): EntityTableConfig<ReportInfo> {
    this.config.componentsData = {};
    return this.config;
  }

  private configureCellActions(): Array<CellActionDescriptor<ReportInfo>> {
    return [
      {
        name: this.translate.instant('report.download'),
        icon: 'file_download',
        isEnabled: () => true,
        onAction: ($event, entity) => this.downloadReport($event, entity)
      }
    ];
  }

  private downloadReport($event: Event, entity: ReportInfo) {
    if ($event) {
      $event.stopPropagation();
    }
    this.reportService.downloadReport(entity.id.id).subscribe({
      error: err => console.error('[Reporting] report download failed', err)
    });
  }
}
